### ISSUE TITLE
Add users total stars in the stats window

### ISSUE THREAD

**Issue by TheWillG** [theblindprophet/github-profile-summary#30]
- [ ] add star counter for total number of stars a user has

**Comment by lgruelas** [comment]
I'm interested

**Comment by himanshu2408** [comment]
Interested

**Comment by theblindprophet** [comment]
@igruelas you had it first.

**Comment by lgruelas** [comment]
Hello, right now the stars feature is pointing to the response starredRepositories.totalCount, that express how many stars I have given to other repositories, is that the desired functionality? I thought that it has to point to totalStars that express how many starts my repositories have received but I am not sure about it.

Also I'm not sure that this is the proper way to ask about this, I just want a clarification to know if I have misunderstand the issue so I don't wanted to open a new issue.

**Comment by theblindprophet** [comment]
Everything is good. We have both features implemented now.
