### ISSUE TITLE
Dialog to email GitHub user

### ISSUE THREAD

**Issue by TheWillG** [theblindprophet/github-profile-summary#31]
- [ ] Button to email GitHub user below profile image
  - [ ] User email must be present to show button (not _Hidden_)
  - [ ] POST to `api/v1/email/user` `{ from, subject, message }`
  - [ ] Popop appears with 3 inputs
    1. from field
    2. subject field
    3. message field
  - [ ] All fields required, email validation for `from` field, limit 500 characters an all fields
  - [ ] Clicking submit sends POST, clears fields, and closes popup

![screen shot 2018-10-02 at 11 27 25 am](https://user-images.githubusercontent.com/7903413/46359156-9b400d80-c636-11e8-89b9-d20475c19816.png)

In collaboration with https://github.com/TheWillG/github-profile-summary-api/issues/26.

**Comment by theblindprophet** [comment]
Updated.

**Comment by mohinderps** [comment]
Okay, I am on it!

**Comment by mohinderps** [comment]
Do I create a generic modal for this at framework level?

**Comment by theblindprophet** [comment]
@mohinderps Use a `<div>`. Nothing special. I already have a popup designed for a different feature that you can copy from. Its in `Home.js` (`id="Home-repopopup"`).

**Comment by mohinderps** [comment]
Okay, Great!

**Comment by theblindprophet** [comment]
@mohinderps Any progress on this? The backend portion is closed to finished.

**Comment by mohinderps** [comment]
Yes, I will be able to finish in some time. Need to add validations on input fields.

**Comment by mohinderps** [comment]
What is the API that I need to POST to?

**Comment by mohinderps** [comment]
Submitted PR #51

**Comment by theblindprophet** [comment]
Moved to #52.

**Comment by theblindprophet** [comment]
@mohinderps Great job on this.
