### ISSUE TITLE
Add UI links for gists and repos

### ISSUE THREAD

**Issue by TheWillG** [theblindprophet/github-profile-summary#35]
Follow the same format as the other buttons on the stats panel that are clickable and lead back to GitHub
- [ ] Make gists button clickable and link to https://gist.github.com/{GITHUB_USERNAME_HERE}
- [ ] Make repos button clickable and link to https://github.com/{GITHUB_USERNAME_HERE}?tab=repositories

**Comment by xBytez** [comment]
Oh I actually really like this project. I'll give this issue a try.

**Comment by theblindprophet** [comment]
@xBytez You got it.
