### ISSUE TITLE
Modify router to accept username

### ISSUE THREAD

**Issue by TheWillG** [theblindprophet/github-profile-summary#43]
Summary: We want developers to be able to easily share their GitHubProfileSummary. It would be very useful to have the React Router parse the username out of the URL like so: `https://githubprofilesummary.com/user/thewillg` where `thewillg` is the username.  
This way, when clicking the link, the GitHubProfileSummary for the user will automatically appear.

- [ ] Add React router routes to handle new path /user/{USER_NAME}
- [ ] Automatically fetch the user's data when app loads if {USER_NAME} is included in path
- [ ] Test to make sure the app automatically renders the correct GitHubProfileSummary

**Comment by peterj** [comment]
Can I take this one?

**Comment by TheWillG** [comment]
It’s all yours @peterj

**Comment by theblindprophet** [comment]
@peterj Great job on this.
