### ISSUE TITLE
Add "copy url" button

### ISSUE THREAD

**Issue by theblindprophet** [theblindprophet/github-profile-summary#47]
- [ ] Add icon using the currently implement icon library to top right of user image
- [ ] Icon should be clickable, pointer
- [ ] When clicked, the user's link should be copied to the user's clipboard in the format `https://githubprofilesummary.com/user/<username>`

**Comment by khuyn003** [comment]
@theblindprophet may I take this one?

**Comment by theblindprophet** [comment]
@khuyn003 You got it.

**Comment by theblindprophet** [comment]
@khuyn003 Great job on this.
