### ISSUE TITLE
Find out why pie chart expands past default width when window expanded

### ISSUE THREAD

**Issue by theblindprophet** [theblindprophet/github-profile-summary#48]
When you expand the window, the chart, which is normally ~400px, expands to be very large.

Needs fixed.

**Comment by arjohnston** [comment]
I'll take this on

**Comment by CoryWritesCode** [comment]
@theblindprophet may I take this one?

**Comment by theblindprophet** [comment]
@CoryWritesCode You got it.

**Comment by CoryWritesCode** [comment]
@theblindprophet Would you like me to fork the repo and apply changes? It won't let me push a commit.

**Comment by theblindprophet** [comment]
@CoryWritesCode Great job on this.

**Comment by CoryWritesCode** [comment]
Thanks for the opportunity @theblindprophet!
