### ISSUE TITLE
Add number of stars to repo list

### ISSUE THREAD

**Issue by theblindprophet** [theblindprophet/github-profile-summary#54]
`stargazers` is a new property that is returned on each repo. It has `totalCount` property.

Display that number along with a `FaStar` on each repo block in the repo list.

![screen shot 2018-10-04 at 7 11 58 am](https://user-images.githubusercontent.com/7903413/46470525-f263f080-c7a4-11e8-8b4d-44424e0dfe77.png)

**Comment by rasfa98** [comment]
Can I try to fix this?

**Comment by theblindprophet** [comment]
@rasfa98 Go for it.

**Comment by theblindprophet** [comment]
@rasfa98 Great job on this.
