### ISSUE TITLE
Add favorite language to `Home-Stats`

### ISSUE THREAD

**Issue by theblindprophet** [theblindprophet/github-profile-summary#57]
There is a property, `topLanguage` returned in the response for a user's info. Add this as another block in the `Home-Stats` section. .e.g `Top Language: JavaScript`

**Comment by joao-p-marques** [comment]
Hi! I'd like to help.
Can you explain a bit more about where the request is made and what files are involved?

**Comment by sajadhsm** [comment]
May I take this one?

**Comment by theblindprophet** [comment]
@joao-p-marques You were first. There is a request made to get the user's info and in that response there is a field, `topLanguage`.

Just check out the code in `Home-Stats.js` and you should be able to quickly figure out what is going on.

**Comment by joao-p-marques** [comment]
OK, thanks.
Working on it.
