### ISSUE TITLE
Setup a verified, tested, and supported React UI testing framework

### ISSUE THREAD

**Issue by theblindprophet** [theblindprophet/github-profile-summary#66]
I would like to slowly begin creating UI tests for this app, however, I am not experienced in such.

I would like to implement a popular UI testing framework. First test can be example, it just needs to work well and be started with `npm run test`.

**Comment by janczizikow** [comment]
I could take a look into this. Would [jest](https://jestjs.io/docs/en/getting-started) with [enzyme](https://airbnb.io/enzyme/) be ok for you?

**Comment by theblindprophet** [comment]
@janczizikow Looks good to me. I have used `jest` before for unit testing.
Just set up a single, very basic test for now.

Thanks.

**Comment by theblindprophet** [comment]
@janczizikow Great work on this. I branched off and made a few changes so I could get the build server working. Excellent work, feel free to add more tests.

**Comment by janczizikow** [comment]
Cool, glad I could help. 🎉
