### ISSUE TITLE
Stub API call to POST a search on a user

### ISSUE THREAD

**Issue by theblindprophet** [theblindprophet/github-profile-summary#69]
- [ ] In `api.js` create an API call (POST) to route `/view/${username}`
- [ ] Empty POST body
- [ ] When a user has **successfully** searched (when search call returns in `Home.js`) make the call specified above

Keep an array inside of `localStorage` that stores the username's that have been searched. Only send the POST as specified above if the username is not in the array. This will prevent user's from spam clicking the search button on their own account to boot view counts.

**Comment by theblindprophet** [comment]
Ask for clarification if needed.

**Comment by sechambers** [comment]
I'd like to take a crack at this. Can you assign it to me? I'll likely get to it over the weekend

**Comment by theblindprophet** [comment]
@sechambers You can have it.

**Comment by schambers** [comment]
Awesome. Will report back with any questions. Ty!

**Comment by schambers** [comment]
whoops. i replied to the comment on my work account. I'll be performing the work on my personal account which is @schambers

**Comment by schambers** [comment]
I haven't had a chance to work on this. Perhaps this evening. If someone else wants to grab it thats fine with me. Sorry for the delay

**Comment by theblindprophet** [comment]
@schambers I have a better way of tackling this anyway, going to close.
